# Generated by Django 5.0.14 on 2025-07-28 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.AutoField(db_column='country_id', primary_key=True, serialize=False)),
                ('country_name', models.CharField(db_column='country_name', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TourPackage',
            fields=[
                ('package_id', models.AutoField(db_column='package_id', primary_key=True, serialize=False)),
                ('package_name', models.CharField(db_column='package_name', max_length=150, unique=True)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('duration_days', models.IntegerField(blank=True, db_column='duration_days', null=True)),
                ('price', models.DecimalField(blank=True, db_column='price', decimal_places=2, max_digits=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(db_column='city_id', primary_key=True, serialize=False)),
                ('city_name', models.CharField(db_column='city_name', max_length=100)),
                ('city_price', models.DecimalField(blank=True, db_column='city_price', decimal_places=2, max_digits=25, null=True)),
                ('stay_duration', models.IntegerField(blank=True, db_column='stay_duration', null=True)),
                ('country', models.ForeignKey(db_column='country', on_delete=django.db.models.deletion.CASCADE, to='trip_package.country')),
            ],
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('spot_id', models.AutoField(db_column='spot_id', primary_key=True, serialize=False)),
                ('spot_name', models.CharField(db_column='spot_name', max_length=150)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('entry_fee', models.DecimalField(blank=True, db_column='entry_fee', decimal_places=2, max_digits=25, null=True)),
                ('timing', models.TimeField(blank=True, db_column='timing', null=True)),
                ('duration', models.DecimalField(blank=True, db_column='duration', decimal_places=4, max_digits=25, null=True)),
                ('day_no', models.IntegerField(blank=True, db_column='day_no', null=True)),
                ('city', models.ForeignKey(db_column='city', on_delete=django.db.models.deletion.CASCADE, to='trip_package.city')),
            ],
        ),
        migrations.CreateModel(
            name='PackageCity',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('sequence', models.IntegerField(blank=True, db_column='sequence', null=True)),
                ('city', models.ForeignKey(db_column='city', on_delete=django.db.models.deletion.CASCADE, to='trip_package.city')),
                ('package', models.ForeignKey(db_column='package', on_delete=django.db.models.deletion.CASCADE, to='trip_package.tourpackage')),
            ],
        ),
    ]
