# Generated by Django 5.0.14 on 2025-07-29 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_package', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripPackageUsers',
            fields=[
                ('user_id', models.AutoField(db_column='user_id', primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, db_column='first_name', max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, db_column='last_name', max_length=100, null=True)),
                ('email', models.CharField(blank=True, db_column='email', max_length=150, null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, db_column='phone_number', max_length=15, null=True)),
                ('password_hash', models.CharField(blank=True, db_column='password_hash', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TripPackageBookings',
            fields=[
                ('booking_id', models.AutoField(db_column='booking_id', primary_key=True, serialize=False)),
                ('booking_date', models.DateTimeField(auto_now_add=True, db_column='booking_date', null=True)),
                ('total_amount', models.DecimalField(blank=True, db_column='total_amount', decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(blank=True, db_column='status', max_length=10, null=True)),
                ('package', models.ForeignKey(db_column='package', on_delete=django.db.models.deletion.CASCADE, to='trip_package.tourpackage')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='trip_package.trippackageusers')),
            ],
        ),
        migrations.CreateModel(
            name='BookingTickets',
            fields=[
                ('ticket_id', models.AutoField(db_column='ticket_id', primary_key=True, serialize=False)),
                ('booking', models.ForeignKey(db_column='booking', on_delete=django.db.models.deletion.CASCADE, to='trip_package.trippackagebookings')),
            ],
        ),
        migrations.CreateModel(
            name='TripPackagePassengers',
            fields=[
                ('passenger_id', models.AutoField(db_column='passenger_id', primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, db_column='full_name', max_length=100, null=True)),
                ('age', models.IntegerField(blank=True, db_column='age', null=True)),
                ('gender', models.CharField(blank=True, db_column='gender', max_length=10, null=True)),
                ('passport_number', models.CharField(blank=True, db_column='passport_number', max_length=20, null=True)),
                ('booking', models.ForeignKey(db_column='booking_id', on_delete=django.db.models.deletion.CASCADE, to='trip_package.trippackagebookings')),
            ],
        ),
    ]
