# Generated by Django 5.0.14 on 2025-08-03 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_package', '0002_trippackageusers_trippackagebookings_bookingtickets_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingtickets',
            name='flight_booking_id',
            field=models.IntegerField(blank=True, db_column='flight_booking_id', null=True),
        ),
    ]
